name: Deploy ke Azure

on:
  push:
    branches: [ "main" ] # Sesuaikan sama branch lu

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Sesuaikan versi PHP lu

    # Langkah ini PENTING biar sertifikat SSL ikut ke-deploy
    - name: Download SSL Cert if missing
      run: |
        if [ ! -f DigiCertGlobalRootG2.crt.pem ]; then
          wget https://dl.cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem
        fi

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webcrudrara' 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .